#!/usr/bin/env bash

ENV_FILE=".env"

# Remove the existing .env file
rm -f "$ENV_FILE"

# Write the variables to the .env file
echo "API_PORT=3030" >> "$ENV_FILE"
echo "REDIS_HOST=localhost" >> "$ENV_FILE"
echo "REDIS_PORT=6380" >> "$ENV_FILE"
echo "REDIS_TTL=300" >> "$ENV_FILE"
echo "SECRET_KEY='3596bece-3609-4292-9ed8-b2881fae4cda'" >> "$ENV_FILE"

# Source the .env file
source "$ENV_FILE"