#!/usr/bin/env bash

ENV_FILE=".env"
rm -f "$ENV_FILE"
touch "$ENV_FILE"
chmod 0755 "$ENV_FILE"
echo "API_PORT=3030" >> "$ENV_FILE"
echo "REDIS_HOST=localhost" >> "$ENV_FILE"
echo "REDIS_PORT=6379" >> "$ENV_FILE"
echo "REDIS_TTL=300" >> "$ENV_FILE"
echo "SECRET_KEY='3596bece-3609-4292-9ed8-b2881fae4cda'" >> "$ENV_FILE"
source "$ENV_FILE"
npm run build
npm run static
npm run start:prod


