#!/usr/bin/env bash

# Import environment variables
source .env

# Define the container names
CONTAINER_REDIS=stone_customer_redis
CONTAINER_API=stone_customer_api
CONTAINER_NETWORK=stone_customer_api_network

if ! docker network ls | grep $CONTAINER_NETWORK; then
	docker network create $CONTAINER_NETWORK
fi

# Run Redis and customer-api containers
if docker ps -a --format '{{.Names}}' | grep $CONTAINER_REDIS; then 
	if docker ps -a --format '{{.Status}}' | grep "Exited"; then 
		docker start $CONTAINER_REDIS
	fi
else
	REDIS_FILE="redis.conf"
	rm -f "$REDIS_FILE"	
	echo "HOST localhost" >> "$REDIS_FILE"
	echo "PORT $REDIS_PORT" >> "$REDIS_FILE"
	docker run -d -v "$REDIS_FILE:/usr/local/etc/redis" -p "$REDIS_PORT:$REDIS_PORT" --network $CONTAINER_NETWORK --name $CONTAINER_REDIS redis /usr/local/etc/redis/redis.conf
fi

if docker ps -a --format '{{.Names}}' | grep $CONTAINER_API; then 
	if docker ps -a --format '{{.Status}}' | grep "Exited"; then 
		docker start $CONTAINER_API
	fi
else
	docker run -e "API_PORT=$API_PORT" -e "REDIS_HOST=redis" -e "REDIS_PORT=$REDIS_PORT" -e "REDIS_TTL=$REDIS_TTL" -e "SECRET_KEY=$SECRET_KEY" -d -p "$API_PORT:$API_PORT" --network "$CONTAINER_NETWORK" --name "$CONTAINER_API" "$CONTAINER_API"
fi
