#!/usr/bin/env bash

# Define the container names
CONTAINER_REDIS=customer_redis
CONTAINER_CUSTOMER_API=customer_api

# Run redis and customer-api containers
docker stop $CONTAINER_REDIS
docker stop $CONTAINER_CUSTOMER_API
