#!/usr/bin/env bash

# Define the image name
IMAGE_API=stone_customer_api
IMAGE_REDIS=redis

# Build dist/ and copy static files
npm run build
npm run static

# Build the image
#docker pull $IMAGE_REDIS
docker rmi -f $IMAGE_API
docker build -t $IMAGE_API .
