#!/usr/bin/env bash

# Define the container names
CONTAINER_REDIS=redis
CONTAINER_API=stone_customer_api

# Remove redis container
if docker ps -a --format '{{.Names}}' | grep $CONTAINER_REDIS; then 
	if docker ps -a --format '{{.Status}}' | grep "Up"; then 
		docker stop $CONTAINER_REDIS
		docker rm -f $CONTAINER_REDIS
		docker rmi -f $CONTAINER_REDIS
	fi
fi

# Remove customer-api container
if docker ps -a --format '{{.Names}}' | grep $CONTAINER_API; then 
	if docker ps -a --format '{{.Status}}' | grep "Up"; then 
		docker stop $CONTAINER_API
		docker rm -f $CONTAINER_API
		docker rmi -f $CONTAINER_API
	fi
fi
