#!/usr/bin/env bash

# Define the container names
CONTAINER_REDIS=redis
CONTAINER_CUSTOMER_API=stone_customer_api

# Run redis and customer-api containers
docker stop $CONTAINER_REDIS
docker stop $CONTAINER_CUSTOMER_API
